# Generated by Django 2.1 on 2020-03-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('maximum_time', models.IntegerField()),
                ('inative', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Livre', 'Livre'), ('Ocupado', 'Ocupado'), ('Atrasado', 'Atrasado')], default='Livre', max_length=9)),
                ('amount_of_loans', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.DateTimeField(blank=True)),
                ('devolution', models.DateTimeField(blank=True, null=True)),
                ('equiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.Equipment')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimo', to='users.Client')),
                ('usuario2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolução', to='users.Client')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='type_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.Equipment_type'),
        ),
    ]
