# Generated by Django 3.1 on 2020-10-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='email_sent',
            field=models.BooleanField(default=True),
        ),
    ]
