# Generated by Django 3.0.4 on 2020-04-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_equipment_user_limit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_type',
            name='inative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='maximum_time',
            field=models.IntegerField(default=4),
        ),
    ]
