# Generated by Django 3.0.4 on 2020-04-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_auto_20200428_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_type',
            name='maximum',
        ),
    ]
