# Generated by Django 3.0.7 on 2020-06-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_equipment_type_time_maximum'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cod_telegram',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
