# Generated by Django 3.0.7 on 2020-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0011_remove_equipment_cod_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='tag',
            field=models.CharField(max_length=10),
        ),
    ]
