# Generated by Django 2.1 on 2020-03-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('whatsapp', models.CharField(max_length=20, null=True)),
                ('cpf', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('Comum', 'Comum'), ('Administrador', 'Administrador'), ('Super', 'Super')], default='Comum', max_length=9)),
                ('senha', models.CharField(max_length=50)),
                ('inative', models.BooleanField(default=False)),
            ],
        ),
    ]
