# Generated by Django 3.0.7 on 2020-07-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_cod_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='client',
            name='user_type',
            field=models.CharField(default='Comum', max_length=13),
        ),
    ]
