# Generated by Django 3.0.4 on 2020-03-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_user',
            name='amount_of_loans',
            field=models.IntegerField(default=0),
        ),
    ]
