# Generated by Django 3.1 on 2020-09-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('user_type', models.CharField(default='Comum', max_length=13)),
                ('senha', models.CharField(max_length=50)),
                ('fingerprint', models.CharField(max_length=1630, null=True, unique=True)),
                ('inative', models.BooleanField(default=False)),
                ('cod_telegram', models.TextField(max_length=10, null=True)),
            ],
        ),
    ]
