# Generated by Django 3.0.4 on 2020-03-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user_type',
            field=models.CharField(choices=[('Comum', 'Comum'), ('Administrador', 'Administrador'), ('Super', 'Super')], default='Comum', max_length=13),
        ),
    ]
