# Generated by Django 3.0.4 on 2020-06-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200428_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fingerprint',
            field=models.CharField(max_length=1630, null=True, unique=True),
        ),
    ]
