# Generated by Django 3.0.7 on 2020-06-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cod_telegram',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
