# Generated by Django 3.0.7 on 2020-08-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200726_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
    ]
