# Generated by Django 2.1.5 on 2020-02-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tag',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.Equipment_type'),
        ),
    ]
