# Generated by Django 2.1.5 on 2020-02-19 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20200219_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.DateTimeField(blank=True)),
                ('devolution', models.DateTimeField(blank=True)),
                ('user', models.CharField(max_length=20)),
                ('equiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.Equipment')),
            ],
        ),
        migrations.AlterField(
            model_name='equipment_type',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
