# Generated by Django 3.0.4 on 2020-04-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_auto_20200402_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_user',
            name='limit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
