# Generated by Django 2.1.5 on 2020-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_auto_20200219_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('cpf', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=9)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
