# Generated by Django 3.0.4 on 2020-04-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_auto_20200413_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_type',
            name='maximum_time',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='maximum_time',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tag',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment_type',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
