# Generated by Django 3.0.4 on 2020-04-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_auto_20200428_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment_type',
            old_name='maximum_time',
            new_name='maximum',
        ),
    ]
