# Generated by Django 2.1.5 on 2020-03-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_user',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.Client'),
        ),
    ]
