# Generated by Django 2.1.5 on 2020-03-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_auto_20200304_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_user',
            name='user',
        ),
        migrations.AddField(
            model_name='equipment_user',
            name='client_devolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_devolution', to='equipments.Client'),
        ),
        migrations.AddField(
            model_name='equipment_user',
            name='client_loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_load', to='equipments.Client'),
        ),
    ]
