# Generated by Django 2.1.5 on 2020-03-10 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_auto_20200305_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment_user',
            name='client_devolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_devolution', to='equipments.Client'),
        ),
    ]
