# Generated by Django 3.0.4 on 2020-04-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_remove_equipment_type_maximum'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_type',
            name='time_maximum',
            field=models.IntegerField(default=0),
        ),
    ]
