# Generated by Django 2.1.5 on 2020-03-10 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_auto_20200310_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
