# Generated by Django 3.0.7 on 2020-06-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_equipment_cod_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='cod_telegram',
        ),
    ]
