# Generated by Django 3.0.7 on 2020-07-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0012_auto_20200702_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='Livre', max_length=9),
        ),
    ]
